name: CI
on: [push]
jobs:
  test_build_run:
    runs-on: self_hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run : |
          pip install pytest
          pytest
      - name: build docker image
        run:
          docker build -t test .
      - name: run docker image
        run:
          docker run test